version: '2'
services:

  ## Config Servers
  config02:
    image: mongo:3.6.4-jessie
    command: mongod --port 27018 --configsvr --replSet configserver
    restart: always
    network_mode: host
    ports:
      - "27018"  
    volumes:
      - ./scripts:/scripts
      - /mongodb/db:/data/db
      - /mongodb/configdb:/data/configdb
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone  
    extra_hosts:
      - "config01:10.40.80.22"
      - "config02:10.40.80.23"
      - "shard01:10.40.80.22"
      - "shard02:10.40.80.23"

  ## Shards
  shard02:
    image: mongo:3.6.4-jessie
    command: mongod --port 27019 --shardsvr --replSet shard02
    restart: always
    network_mode: host
    ports:
      - "27019"
    volumes:
      - ./scripts:/scripts
      - /mongodb/db:/data/db
      - /mongodb/configdb:/data/configdb
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone      
    extra_hosts:
      - "config01:10.40.80.22"
      - "config02:10.40.80.23"
      - "shard01:10.40.80.22"
      - "shard02:10.40.80.23"   

  ## Router
  router02:
    image: mongo:3.6.4-jessie
    command: mongos --port 27017 --configdb configserver/config01:27018,config02:27018 --bind_ip_all
    restart: always
    network_mode: host
    ports:
      - "27017"
    volumes:
      - ./scripts:/scripts
      - /mongodb/db:/data/db
      - /mongodb/configdb:/data/configdb
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone      
    extra_hosts:
      - "config01:10.40.80.22"
      - "config02:10.40.80.23"
      - "shard01:10.40.80.22"
      - "shard02:10.40.80.23"          
    depends_on:
      - config02
      - shard02
