version: '2'
services:

  ## Config Servers
  config01:
    image: mongo:3.6.4-jessie
    command: mongod --port 27018 --configsvr --replSet configserver
    restart: always
    network_mode: host
    ports:
      - "27018"  
    volumes:
      - ./scripts:/scripts
      - /mongodb/config01/db:/data/db
      - /mongodb/config01/configdb:/data/configdb
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone  
    extra_hosts:
      - "config01:10.40.80.25"
      - "config02:10.40.80.26"
      - "shard01:10.40.80.25"
      - "shard02:10.40.80.26"

  ## Shards
  shard01:
    image: mongo:3.6.4-jessie
    command: mongod --port 27019 --shardsvr --replSet shard01
    restart: always
    network_mode: host
    ports:
      - "27019"
    volumes:
      - ./scripts:/scripts
      - /mongodb/shard01/db:/data/db
      - /mongodb/shard01/configdb:/data/configdb
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone      
    extra_hosts:
      - "config01:10.40.80.25"
      - "config02:10.40.80.26"
      - "shard01:10.40.80.25"
      - "shard02:10.40.80.26"   

  ## Router
  router01:
    image: mongo:3.6.4-jessie
    command: mongos --port 27017 --configdb configserver/config01:27018,config02:27018 --bind_ip_all
    restart: always
    network_mode: host
    ports:
      - "27017"
    volumes:
      - ./scripts:/scripts
      - /mongodb/router01/db:/data/db
      - /mongodb/router01/configdb:/data/configdb
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone      
    extra_hosts:
      - "config01:10.40.80.25"
      - "config02:10.40.80.26"
      - "shard01:10.40.80.25"
      - "shard02:10.40.80.26"          
    depends_on:
      - config01
      - shard01
